- src/main/java/com/oti/team2/exampleController.java
- src/main/webapp/WEB-INF/views/board/notice-detail.jsp
- src/main/webapp/WEB-INF/views/board/noticeList.jsp
- src/main/webapp/WEB-INF/views/board/qna-detail.jsp
- src/main/webapp/WEB-INF/views/board/qnaList.jsp
- src/main/webapp/WEB-INF/views/fragments/header.jsp
- src/main/webapp/WEB-INF/views/history/addHistoryModalDetail.jsp
- src/main/webapp/WEB-INF/views/srDemand/modal.jsp
- src/main/webapp/WEB-INF/views/srDemand/srDemandList.jsp
- src/main/webapp/WEB-INF/views/srDemand/srDemandList2.jsp
- src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
> [#4] 검사 전 합치기

- .gitignore
- src/main/resources/database/jdbc.properties
> jdbc.properties ignore 해제

- .settings/org.eclipse.wst.common.component
- src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
- src/main/resources/mybatis/mapper/member.xml
- src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
> sr진척 목록 상세 충돌 해결

- src/main/webapp/WEB-INF/views/member/my-todo.jsp
- src/main/webapp/WEB-INF/views/srDemand/userSrDemandList.jsp
> [#40] pageContext 추가

- src/main/webapp/WEB-INF/views/fragments/bottom.jsp
- src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
- src/main/webapp/resources/assets/js/addSrResourcesModal.js
- src/main/webapp/resources/js/employeesList.js
- src/main/webapp/resources/js/getContextPath.js
- src/main/webapp/resources/js/srResources.js
> contextPath 함수 추가

- src/main/java/com/oti/team2/progress/controller/ProgressController.java
- src/main/java/com/oti/team2/progress/dao/IProgressDao.java
- src/main/java/com/oti/team2/progress/dto/Progress.java
- src/main/java/com/oti/team2/progress/service/IProgressService.java
- src/main/java/com/oti/team2/progress/service/ProgressService.java
- src/main/java/com/oti/team2/srdemand/controller/SrDemandController.java
- src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
- src/main/java/com/oti/team2/srinformation/dto/SrdemandDetail.java
- src/main/resources/mybatis/mapper/progress.xml
- src/main/resources/mybatis/mapper/srDemand.xml
- src/main/webapp/WEB-INF/views/fragments/header.jsp
- src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
- src/main/webapp/resources/js/onclickTr.js
> [#37] Feature 37

- .springBeans
- pom.xml
- src/main/java/com/oti/team2/exampleController.java
- src/main/java/com/oti/team2/member/controller/LoginController.java
- src/main/java/com/oti/team2/member/dao/IMemberDao.java
- src/main/java/com/oti/team2/member/dto/Member.java
- src/main/java/com/oti/team2/member/dto/Users.java
- src/main/java/com/oti/team2/member/service/UserService.java
- src/main/java/com/oti/team2/util/springsecurity/AuthenticationFailureHandler.java
- src/main/java/com/oti/team2/util/springsecurity/AuthenticationSuccessHandler.java
- src/main/java/com/oti/team2/util/springsecurity/LogoutSuccessHandler.java
- src/main/java/com/oti/team2/util/springsecurity/MyPasswordEncoder.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/member.xml
- src/main/resources/spring/security.xml
- src/main/webapp/WEB-INF/views/fragments/sidebar.jsp
- src/main/webapp/WEB-INF/views/fragments/top.jsp
- src/main/webapp/WEB-INF/views/member/login.jsp
- src/main/webapp/WEB-INF/web.xml
> [#57] Spring Security를 사용해 로그인/로그아웃 기능 구현

- src/main/java/com/oti/team2/admin/controller/AdminController.java
- src/main/java/com/oti/team2/member/controller/MemberController.java
- src/main/java/com/oti/team2/member/dao/IMemberDao.java
- src/main/java/com/oti/team2/member/dto/FilteringMember.java
- src/main/java/com/oti/team2/member/service/IMemberService.java
- src/main/java/com/oti/team2/member/service/MemberService.java
- src/main/java/com/oti/team2/srdemand/controller/SrDemandController.java
- src/main/java/com/oti/team2/util/Auth.java
- src/main/resources/mybatis/mapper/member.xml
- src/main/webapp/WEB-INF/views/fragments/header.jsp
- src/main/webapp/WEB-INF/views/management/employeesList.jsp
고객 관리 페이지와 같은 서비스를 사용하여 컨트롤러를 일부 수정함
> [#30] 사원 관리 페이지 검색 및 페이징 기능 추가

- src/main/java/com/oti/team2/exampleController.java
- src/main/java/com/oti/team2/srdemand/controller/SrDemandController.java
- src/main/java/com/oti/team2/srinformationhistory/controller/SrInformationHistoryController.java
- src/main/java/com/oti/team2/srinformationhistory/dto/SrHistoryDetailDto.java
- src/main/resources/mybatis/mapper/srDemand.xml
- src/main/resources/mybatis/mapper/srInformationHistory.xml
- src/main/resources/mybatis/mapper/srinformation.xml
- src/main/webapp/WEB-INF/views/history/addHistoryModal.jsp
- src/main/webapp/WEB-INF/views/history/approvalHistoryModal.jsp
- src/main/webapp/WEB-INF/views/srDemand/adminSrDemandList.jsp
> [#41] 충돌 해결 후 PR

- src/main/java/com/oti/team2/admin/controller/AdminController.java
- src/main/java/com/oti/team2/member/dao/IMemberDao.java
- src/main/java/com/oti/team2/member/dto/FilterDto.java
- src/main/java/com/oti/team2/member/service/IMemberService.java
- src/main/java/com/oti/team2/member/service/MemberService.java
- src/main/java/com/oti/team2/role/controller/RoleController.java
- src/main/java/com/oti/team2/role/dao/IRoleDao.java
- src/main/java/com/oti/team2/role/dto/Role.java
- src/main/java/com/oti/team2/role/service/IRoleService.java
- src/main/java/com/oti/team2/role/service/RoleService.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/role.xml
- src/main/resources/spring/mybatis.xml
- src/main/resources/spring/security.xml
- src/main/webapp/WEB-INF/views/srInfo/addSrResourcesModal.jsp
- src/main/webapp/resources/js/addSrResourcesModal.js
개발자 역할 목록 조회 기능 추가
모달 닫은 후 날짜 입력 값 초기화
자원 정보 추가 후 일정 업데이트
> [#39]자원 정보 추가 모달에서 개발자 역할 목록 조회 기능 추가 

- src/main/java/com/oti/team2/progress/dao/IProgressDao.java
- src/main/java/com/oti/team2/progress/service/IProgressService.java
- src/main/java/com/oti/team2/progress/service/ProgressService.java
- src/main/java/com/oti/team2/srdemand/dao/ISrDemandDao.java
- src/main/java/com/oti/team2/srdemand/service/ISrDemandService.java
- src/main/java/com/oti/team2/srdemand/service/SrDemandService.java
- src/main/resources/mybatis/mapper/progress.xml
- src/main/resources/mybatis/mapper/srDemand.xml
수한님이 기존에 구현하신 srDemand 상태 변경 메소드를 재사용하여
개발 취소시 (sr번호,6) 값을 보내주시면 됩니다.
** 기존에 위의 쿼리가 progess 에 있어 ->srDemand로 옮겼습니다!
> [#70]SR히스토리 : 개발취소 승인 시 sr요청 상태 변경

- src/main/java/com/oti/team2/deliverable/controller/DeliverableController.java
- src/main/java/com/oti/team2/deliverable/dao/IDeliverableDao.java
- src/main/java/com/oti/team2/deliverable/service/DeliverableService.java
- src/main/java/com/oti/team2/deliverable/service/IDeliverableService.java
- src/main/java/com/oti/team2/srresource/controller/SrResourceController.java
- src/main/java/com/oti/team2/srresource/dao/ISrResourceDao.java
- src/main/java/com/oti/team2/srresource/dto/SrResource.java
- src/main/java/com/oti/team2/srresource/dto/SrResourceOfDeveloper.java
- src/main/java/com/oti/team2/srresource/service/ISrResourceService.java
- src/main/java/com/oti/team2/srresource/service/SrResourceService.java
- src/main/resources/mybatis/mapper/deliverable.xml
- src/main/resources/mybatis/mapper/srResource.xml
- src/main/webapp/WEB-INF/views/srInfo/addSrResourcesModal.jsp
- src/main/webapp/resources/js/addSrResourcesModal.js
- src/main/webapp/resources/js/deliverables.js
- src/main/webapp/resources/js/srInfo.js
- src/main/webapp/resources/js/srResources.js
> [#55]산출물 수정 기능 구현

- src/main/java/com/oti/team2/admin/controller/AdminController.java
- src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
- src/main/java/com/oti/team2/srinformation/dao/ISrinformationDao.java
- src/main/java/com/oti/team2/srinformation/dto/SrInfoFilter.java
- src/main/java/com/oti/team2/srinformation/service/ISrinformationService.java
- src/main/java/com/oti/team2/srinformation/service/SrinformationService.java
- src/main/java/com/oti/team2/util/pager/Pager.java
- src/main/resources/mybatis/mapper/member.xml
- src/main/resources/mybatis/mapper/srResource.xml
- src/main/resources/mybatis/mapper/srinformation.xml
- src/main/webapp/WEB-INF/views/fragments/pagination.jsp
- src/main/webapp/WEB-INF/views/management/employeesList.jsp
- src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
- src/main/webapp/resources/css/pagination.css
- src/main/webapp/resources/js/employeesList.js
- src/main/webapp/resources/js/pagination.js
- src/main/webapp/resources/js/srInfo.js
- src/main/webapp/resources/js/srResources.js
> [#63] 페이징, 필터링 동시 유지 및 사원관리 페이징 offset으로 수정

- src/main/java/com/oti/team2/admin/controller/AdminController.java
- src/main/java/com/oti/team2/institution/controller/InstitutionController.java
- src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
- src/main/java/com/oti/team2/srresource/controller/SrResourceController.java
- src/main/resources/mybatis/mapper/member.xml
- src/main/resources/spring/security.xml
- src/main/webapp/WEB-INF/views/management/clientList.jsp
- src/main/webapp/resources/js/clientList.js
RequestMapping 을 사용하던 코드를 GetMapping으로 변경
> 고객 관리 필터링 적용 및 컨트롤러 mapping방식 통일

- src/main/java/com/oti/team2/exampleController.java
- src/main/java/com/oti/team2/member/controller/LoginController.java
- src/main/java/com/oti/team2/member/controller/MainController.java
- src/main/java/com/oti/team2/member/service/UserService.java
- src/main/java/com/oti/team2/srdemand/controller/SrDemandController.java
- src/main/java/com/oti/team2/srdemand/dao/ISrDemandDao.java
- src/main/java/com/oti/team2/srdemand/dto/MytodoSrListDto.java
- src/main/java/com/oti/team2/srdemand/service/ISrDemandService.java
- src/main/java/com/oti/team2/srdemand/service/SrDemandService.java
- src/main/java/com/oti/team2/srinformation/service/ISrinformationService.java
- src/main/java/com/oti/team2/srinformation/service/SrinformationService.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/srDemand.xml
- src/main/webapp/WEB-INF/views/fragments/header.jsp
- src/main/webapp/WEB-INF/views/fragments/pagination.jsp
- src/main/webapp/WEB-INF/views/member/my-todo.jsp
- src/main/webapp/WEB-INF/views/srDemand/adminSrDemandList.jsp
- src/main/webapp/resources/js/mytodo.js
- src/main/webapp/resources/js/pagination.js
- 고객/ 관리자/ 개발자 별 나의할일 데이터 조회
- ajax 통신 후 응답객체로 다시 pager 을 생성하는 js 구현 완료 (아래 comment를 확인해주세요!)
> [#73] 고객/관리자/개발자변 나의 할일 화면 데이터 구성 구현 완료

- src/main/java/com/oti/team2/progress/dao/IProgressDao.java
- src/main/java/com/oti/team2/progress/service/IProgressService.java
- src/main/java/com/oti/team2/progress/service/ProgressService.java
- src/main/java/com/oti/team2/srdemand/dto/SdApprovalDto.java
- src/main/java/com/oti/team2/srdemand/service/ISrDemandService.java
- src/main/java/com/oti/team2/srdemand/service/SrDemandService.java
- src/main/java/com/oti/team2/srinformation/service/SrinformationService.java
- src/main/resources/mybatis/mapper/progress.xml
insert all 동적쿼리 사용하여 진척률 삽입 구현 완료
> [#80] insert all 동적쿼리 사용하여 진척률 삽입 구현 완료

- src/main/java/com/oti/team2/alert/controller/AlertController.java
- src/main/java/com/oti/team2/alert/dto/Alert.java
- src/main/java/com/oti/team2/alert/service/AlertService.java
- src/main/java/com/oti/team2/alert/service/IAlertService.java
- src/main/java/com/oti/team2/srresource/controller/SrResourceController.java
- src/main/java/com/oti/team2/srresource/dto/SrResource.java
- src/main/java/com/oti/team2/srresource/service/ISrResourceService.java
- src/main/java/com/oti/team2/srresource/service/SrResourceService.java
- src/main/java/com/oti/team2/util/sseemitter/SseEmitters.java
- src/main/resources/mybatis/mapper/progress.xml
- src/main/webapp/WEB-INF/views/fragments/top.jsp
- src/main/webapp/resources/js/addSrResourcesModal.js
자원 정보가 없을 때 추가 시 개발 중으로 상태가 변경되므로 자원 정보를  전부 삭제 후 추가할 때를 고려 해야 함
> [#39] 처음 자원 정보 입력시 개발중으로 상태 변경

- pom.xml
- src/main/java/com/oti/team2/member/controller/MemberController.java
- src/main/java/com/oti/team2/member/dao/IMemberDao.java
- src/main/java/com/oti/team2/member/dto/MemberDto.java
- src/main/java/com/oti/team2/member/service/IJoinService.java
- src/main/java/com/oti/team2/member/service/IMemberService.java
- src/main/java/com/oti/team2/member/service/JoinService.java
- src/main/java/com/oti/team2/member/service/MemberService.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/member.xml
- src/main/resources/spring/mailsender.xml
- src/main/resources/spring/security.xml
- src/main/webapp/WEB-INF/views/member/findPwModal.jsp
- src/main/webapp/resources/js/findPwModal.js
> [#119] 비밀번호 찾기 구현 완료 및 취합

- src/main/java/com/oti/team2/admin/controller/AdminController.java
- src/main/java/com/oti/team2/department/dto/DeptFilterDto.java
- src/main/webapp/WEB-INF/views/board/notice-detail.jsp
- src/main/webapp/WEB-INF/views/board/noticeList.jsp
- src/main/webapp/WEB-INF/views/board/qna-detail.jsp
- src/main/webapp/WEB-INF/views/board/qnaList.jsp
- src/main/webapp/WEB-INF/views/management/clientList.jsp
- src/main/webapp/WEB-INF/views/management/departmentsList.jsp
- src/main/webapp/WEB-INF/views/management/employeesList.jsp
- src/main/webapp/WEB-INF/views/management/modalDeptManagementRegister.jsp
- src/main/webapp/WEB-INF/views/member/my-todo.jsp
- src/main/webapp/WEB-INF/views/member/myInst.jsp
- src/main/webapp/WEB-INF/views/member/myinfo.jsp
- src/main/webapp/WEB-INF/views/srDemand/adminSrDemandList.jsp
- src/main/webapp/WEB-INF/views/srDemand/userSrDemandList.jsp
- src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
- src/main/webapp/resources/assets/css/style.css
회원관리 파트 화면 수정 및 게시판 상세보기 헤더 복구
> [#124] 회원관리 파트 화면 수정 및 게시판 상세보기 헤더 복구

- src/main/java/com/oti/team2/alert/service/AlertService.java
- src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
- src/main/java/com/oti/team2/srinformation/dao/ISrinformationDao.java
- src/main/java/com/oti/team2/srinformation/service/ISrinformationService.java
- src/main/java/com/oti/team2/srinformation/service/SrinformationService.java
- src/main/resources/mybatis/mapper/srinformation.xml
> [#64]관리자, 나의 처리 보기로 담당 시스템 진척이 나오도록 수정, 알람을 눌렀을때 사라지지않도록 수정

- src/main/java/com/oti/team2/member/controller/MemberController.java
- src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
- src/main/resources/mybatis/mapper/srInformationHistory.xml
- src/main/webapp/resources/js/approvalHstryModal.js
- src/main/webapp/resources/js/approvalInfoHstryModal.js
- src/main/webapp/resources/js/srInfo.js
> [#142] srInfo 개발자 버튼 복구 및 모달 수정

- src/main/java/com/oti/team2/member/controller/MemberController.java
- src/main/java/com/oti/team2/member/dao/IMemberDao.java
- src/main/java/com/oti/team2/srinformation/controller/SrinformationController.java
- src/main/java/com/oti/team2/srinformationhistory/dto/SrHistoryDetailDto.java
- src/main/java/com/oti/team2/srinformationhistory/dto/SrInformationHistory.java
- src/main/webapp/WEB-INF/views/history/approvalHistoryModal.jsp
- src/main/webapp/WEB-INF/views/history/approvalInfoHistoryModal.jsp
- src/main/webapp/WEB-INF/views/member/findPwModal.jsp
- src/main/webapp/WEB-INF/views/srInfo/srInformationList.jsp
- src/main/webapp/resources/js/approvalHstryModal.js
- src/main/webapp/resources/js/approvalInfoHstryModal.js
- src/main/webapp/resources/js/findPwModal.js
> [#144] 비밀번호 찾기, 히스토리 수정 기능 보완 및 취합

- src/main/java/com/oti/team2/srinformation/dto/SrColFilterDto.java
- src/main/java/com/oti/team2/util/springsecurity/AuthenticationSuccessHandler.java
- src/main/resources/mybatis/mapper/srinformation.xml
- src/main/resources/spring/security.xml
> 진척 목록 조회 코드 수정

- src/main/webapp/resources/js/addSrResourcesModal.js
> 자원 정보 모달 열릴시 역할 목록 보이도록 수정

- src/main/java/com/oti/team2/srdemand/service/SrDemandService.java
- src/main/webapp/WEB-INF/views/srDemand/userSrDemandList.jsp
- src/main/webapp/resources/js/approvalInfoHstryModal.js
> [#156] 취합 후 include된 js 수정

- src/main/webapp/WEB-INF/views/mytodo/srTable.jsp
> mytodo 행 클릭시 페이지 이동

- src/main/java/com/oti/team2/util/springsecurity/AuthenticationSuccessHandler.java
- src/main/webapp/resources/js/srDemand.js
> 로그인시 마다 sseemitter생성되지 않도록 수정
